name: Serverless Platform CI/CD

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    
    services:
      mongodb:
        image: mongo:4.4
        ports:
          - 27017:27017

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install root dependencies
      run: npm install
      
    - name: Install API dependencies
      working-directory: ./api
      run: npm install
      
    - name: Install Execution Engine dependencies
      working-directory: ./execution-engine
      run: npm install
      
    - name: Check if dashboard directory exists
      id: check_dashboard
      run: |
        if [ -d "dashboard" ]; then
          echo "::set-output name=exists::true"
        else
          echo "::set-output name=exists::false"
        fi
      
    - name: Install Dashboard dependencies
      if: steps.check_dashboard.outputs.exists == 'true'
      working-directory: ./dashboard
      run: npm install
    
    - name: Lint API code
      working-directory: ./api
      run: |
        npm install eslint --save-dev || true
        npx eslint --init -y || true
        npx eslint . --ext .js || true
    
    - name: Lint Execution Engine code
      working-directory: ./execution-engine
      run: |
        npm install eslint --save-dev || true
        npx eslint --init -y || true
        npx eslint . --ext .js || true
    
    - name: Lint Dashboard code
      if: steps.check_dashboard.outputs.exists == 'true'
      working-directory: ./dashboard
      run: |
        npm install eslint --save-dev || true
        npx eslint --init -y || true
        npx eslint src/ --ext .js,.jsx || true
    
    - name: Run API tests
      working-directory: ./api
      run: npm test || true
      
    - name: Run Execution Engine tests
      working-directory: ./execution-engine
      run: npm test || true
      
    - name: Run Dashboard tests
      if: steps.check_dashboard.outputs.exists == 'true'
      working-directory: ./dashboard
      run: npm test -- --passWithNoTests || true
